### ISSUE TITLE
Defer `community` check

### ISSUE THREAD

**Issue by SichangHe** [SichangHe/parse_rpsl_policy#16]
ASes can change `community`s using `<action>`s. From the BGP dump, we get the final view of `community`, but the ASes on AS path see `community` at their stage, so we would need to backtrack how the `community` is when each AS sees it.

Considering `community.contains` is only used tens of time in RIPE.db (https://github.com/SichangHe/parse_rpsl_policy/issues/3#issuecomment-1592119709), I will defer checking it.

**Comment by cunha** [comment]
To elaborate further, checking for communities is going to be hopeless
because ASes in between the path can remove communities from the
announcement. So there is no guarantee that we will see the
communities on the BGP dumps. (To make matters worse, Cisco routers
remove BGP communities from announcements by default.)
